/**
 * Class challenge Day 4 2022
 *
 * @author    Rafa Hernandez
 * @created   December 2022
 */
public with sharing class AOC2022_Day4 extends AOC_BaseUtils {
  public AOC2022_Day4() {
    this.processInputLines('AOC2022_Day4_Example');
  }

  /**
   * @method : run
   * @return : void method to run the code using anonymous apex script.
   */
  public void run() {
    part1();
    part2();
  }

  /**
   * @method : Part1
   * @return : void method which return debug for part1 solution
   */
  private void part1() {
    //some logic
  }

  /**
   * @method : Part2
   * @return : void method which return debug for part2 solution
   */
  private void part2() {
    //some logic
  }
}
